export class Constants {
  // 文字滚动速度
  public static readonly DEFAULT_SPEED: number = 6
  // 默认文字大小
  public static readonly DEFAULT_FOUNT_SIZE: number = 14
  // 当父容器空间不足时，子元素的压缩比例
  public static readonly FLEX_SHRINK_ZERO: number = 0
  // 最大行数
  public static readonly ONE_LINE: number = 1
  // 最大行数
  public static readonly LAYOUT_WEIGHT_ONE: number = 1
  // 文字宽度
  public static readonly FULL_WIDTH: string = '100%'
  // 右侧查看更多padding
  public static readonly NO_SPACE: number = 0
  // 右侧close图标margin
  public static readonly ICON_SPACE: number = 5
  // 通告栏padding
  public static readonly BAR_PADDING_VERTICAL: number = 10
  public static readonly BAR_PADDING_HORIZONTAL: number = 12
  // 分割器margin
  public static readonly DIVIDER_MARGIN: number = 2
  // 走马灯微调padding
  public static readonly MARQUEE_PADDING: number = 2
}